apiVersion: v2
appVersion: latest
description: Secret for Sausage-Store
home: https://gitlab.praktikum-services.ru/a.mosievskih/momo-store/-/tree/v1.0.0/infrastructure/k8s/helm-chart/momo-store/charts/secret
icon: https://habrastorage.org/r/w1560/webt/_z/dv/dm/_zdvdmex3jobksmq8pmhuscdcww.png
name: secret
version: 0.1.0
