variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
  HELM_CHART_VERSION: 0.1.92122
  SAST_EXCLUDED_ANALYZERS: "eslint,gosec,nodejs-scan"
  
image: golang:1.18

include:
  - template: Security/SAST.gitlab-ci.yml
  - project: 'templates/ci'
    file: 'DockerInDockerTemplate.yml'

stages:
  - build
  - test
  - sonar
  - release
  - deploy

build:
  stage: build
  script:
    - cd backend
    - mkdir -p bin
    - go build -o bin ./...
    - cd .. 
    - mkdir momo-store-${VERSION}
    - mv backend/bin/api momo-store-${VERSION}/momo-store-backend-${VERSION}
  artifacts:
    paths:
      - momo-store-${VERSION}/momo-store-backend-${VERSION}

dockerize-backend:
  stage: build
  image: docker:20.10.12-dind-rootless
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd backend
    - >
      docker build
      --build-arg VERSION=$VERSION
      --tag $CI_REGISTRY_IMAGE/momo-store-backend:$CI_COMMIT_SHA
      .
    - docker push $CI_REGISTRY_IMAGE/momo-store-backend:$CI_COMMIT_SHA

test:
  stage: test
  script:
    - cd backend
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)
    - go test -v ./... 

sonar-scan-backend:
  stage: test
  image:
    name: sonarsource/sonar-scanner-cli:4.4
    entrypoint: [""]
  variables:
    SONAR_TOKEN: "${SONARQUBE_TOKEN}"
    SONAR_HOST_URL: "${SONARQUBE_URL}"
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - cd backend
    - sonar-scanner -Dversion.application=${VERSION} -Dsonar.qualitygate.wait=true -Dsonar.projectKey=07_MOSIEVSKIKH_MOMO_STORE_STORE_BACKEND -Dsonar.projectName=07_MOSIEVSKIKH_MOMO_STORE_BACKEND
  allow_failure: true

release:
  stage: release
  script:
    - tar czvf momo-store-${VERSION}.tar.gz momo-store-${VERSION}/momo-store-backend-${VERSION}
    - curl -v -u "${NEXUS_REPO_USER}:${NEXUS_REPO_PASS}" --upload-file momo-store-${VERSION}.tar.gz ${NEXUS_REPO_URL}/repository/momo-store-mosievskikh-backend/${VERSION}/momo-store-${VERSION}.tar.gz

docker-upload-backend-latest:
  variables:
    GIT_STRATEGY: none
  image: docker:20.10.12-dind-rootless
  stage: release
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE/momo-store-backend:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE/momo-store-backend:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE/momo-store-backend:${VERSION}-$CI_COMMIT_BRANCH
    - docker push $CI_REGISTRY_IMAGE/momo-store-backend:${VERSION}-$CI_COMMIT_BRANCH

deploy:
  stage: deploy
  image: alpine/k8s:1.22.6
  when: manual
  script:
    - curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
    - /root/yandex-cloud/bin/yc config set token ${YC_TOKEN}
    - /root/yandex-cloud/bin/yc managed-kubernetes cluster get-credentials --id cat7fchd6l3o8l81cr10 --external --folder-id b1g51tbhhb88qrbd3qj7
    - helm repo add 	momo-store-helm-a-mosievskih-07 https://nexus.praktikum-services.ru/repository/momo-store-helm-a-mosievskih-07/ --username ${NEXUS_REPO_USER} --password ${NEXUS_REPO_PASS}
    - helm get values momo-store -a -n production > existing_values.yaml
    - helm upgrade --install momo-store momo-store-helm-a-mosievskih-07/momo-store -n production --version ${HELM_CHART_VERSION} -f existing_values.yaml --set=backend.image.tag=${VERSION}-$CI_COMMIT_BRANCH
