---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dump-conf
data:
  default.conf: |
    server {

      listen 80;

      location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
      }

      location /categories {
      proxy_pass http://backend:8081;
      }

      location /products {
      proxy_pass http://backend:8081;
      }

      location /auth {
      proxy_pass http://backend:8081;
      }
    }
