---
apiVersion: v1
kind: Secret
metadata:
  name: docker-config-secret
  labels:
    app: docker-config-secret
data:
  .dockerconfigjson: {{ .Values.global.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson
