### Секрет, необходимый, чтобы взаимодействовать с докер-реджистри в Гитлабе:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    {{ .Values.global.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson
