---
---
apiVersion: v2
type: application
name: pelmennaya2
description: Pelmennaya Helm Chart

appVersion: "latest"

dependencies:
  - name: backend
    version: "~1.0.0"
  - name: frontend
    version: "~1.0.1"
  - name: secret
    version: "~1.0.0"

version: 1.0.10

