---
stages:
  - build
  - deploy

build:
  stage: build
  image: alpine/k8s:1.22.6
  script:
    - |
      sed -i "s/0\.1\.2/$VERSION/g" infrastructure/k8s/helm-chart/momo-store/Chart.yaml
      helm package ./infrastructure/k8s/helm-chart/momo-store/
      curl -u ${NEXUS_REPO_USER}:${NEXUS_REPO_PASS} https://nexus.praktikum-services.ru/repository/momo-store-helm-a-mosievskih-07/ --upload-file momo-store-${VERSION}.tgz

deploy:
  stage: deploy
  image: alpine/k8s:1.22.6
  when: manual
  script:
    - curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
    - /root/yandex-cloud/bin/yc config set token ${YC_TOKEN}
    - /root/yandex-cloud/bin/yc managed-kubernetes cluster get-credentials --id b1g7jn7va51ie1na46qt --external --folder-id b1gja3q0vkl04tb3cc71
    - helm repo add momo-store-helm-a-mosievskih-07 https://nexus.praktikum-services.ru/repository/momo-store-helm-a-mosievskih-07/ --username ${NEXUS_REPO_USER} --password ${NEXUS_REPO_PASS}
    - helm upgrade --install momo-store momo-store-helm-a-mosievskih-07/momo-store -n production --version 0.1.${CI_PIPELINE_ID}

