stages:
  - helm-job

helm-job:
  stage: helm-job
  script:
    - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
    - cd infrastructure/kubernetes/helm-chart
    - helm package --dependency-update momo-store/
    - >
      export VERSION=$(grep -oP 'version: \"(\d+\.\d+\.\d+)\"' momo-store/Chart.yaml | sed 's/version: //' | sed 's/\"//g')
- curl -v -u "${NEXUS_REPO_USER}:${NEXUS_REPO_PASS}" --upload-file momo-store-${VERSION}.tgz ${NEXUS_REPO_URL}/momo-store-helm-a-mosievskih-07/momo-store-${VERSION}.tgz
